LOAD DATABASE
     FROM sqlite:////home/narek/PyCharmMiscProject/Ardar_Blog/db.sqlite3
     INTO postgresql://narek:narek1234@localhost:5432/narek_migrated

  WITH include no drop,
       create tables,
       create indexes,
       reset sequences

  EXCLUDING TABLE NAMES LIKE 'django_migrations'
;
