# Generated by Django 5.1.7 on 2025-03-31 19:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('data_category', models.CharField(choices=[('personal', 'Personal Data'), ('contact', 'Contact Information'), ('financial', 'Financial Data'), ('behavioral', 'Behavioral Data'), ('technical', 'Technical Data')], max_length=50)),
                ('purpose', models.TextField()),
                ('retention_period', models.CharField(max_length=100)),
                ('storage_location', models.CharField(choices=[('db', 'Primary Database'), ('backup', 'Backup Storage'), ('analytics', 'Analytics Service'), ('crm', 'CRM System'), ('marketing', 'Marketing Platform')], max_length=50)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('collected_from', models.CharField(max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Inventory',
                'verbose_name_plural': 'Data Inventory',
                'ordering': ['data_category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DataSubjectRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('access', 'Data Access Request'), ('rectification', 'Data Rectification'), ('erasure', 'Right to be Forgotten'), ('restriction', 'Restriction of Processing'), ('portability', 'Data Portability'), ('object', 'Right to Object')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('request_data', models.JSONField(default=dict)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gdpr_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Subject Request',
                'verbose_name_plural': 'Data Subject Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GDPRConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('privacy_policy', 'Privacy Policy'), ('terms_of_service', 'Terms of Service'), ('marketing', 'Marketing Communications'), ('cookies', 'Cookie Consent'), ('analytics', 'Analytics Tracking')], max_length=50)),
                ('granted', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gdpr_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GDPR Consent',
                'verbose_name_plural': 'GDPR Consents',
                'unique_together': {('user', 'consent_type')},
            },
        ),
    ]
