"""
Django settings for ardar_blog_backend project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from oauth2_provider import settings as oauth2_settings
from dotenv import load_dotenv
from celery.schedules import crontab
from django.utils.translation import gettext_lazy as _



BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!


ALLOWED_HOSTS = ['ardar-blog.onrender.com']
#
# ALLOWED_HOSTS = ['Narek330333.pythonanywhere.com']




CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'



CELERY_BEAT_SCHEDULE = {
    'update-currency-every-day': {
        'task': 'products.tasks.update_currency_exchange_rates',
        'schedule': crontab(hour=0, minute=0),  # Կթարմացվի ամեն օր կեսգիշերին
    },
}



INSTALLED_APPS = [

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django_filters',
    'corsheaders',
    'taggit',
    'accounts',
    'rest_framework',
    'rest_framework.authtoken',


    'authemail',
    'oauth2_provider',
    'drf_social_oauth2',
    'social_django',
    'model_utils',
    'django_extensions',






    # 'dj_rest_auth',
    # 'dj_rest_auth.registration',

    'coupon.apps.CouponConfig',
    'users.apps.UsersConfig',
    'shop.apps.ShopConfig',
    # 'orders.apps.OrdersConfig',
    'cart.apps.CartConfig',
    'orders.apps.OrdersConfig',
    'paypal.standard.ipn',
    'gdpr.apps.GdprConfig',
    'erp.apps.ErpConfig',
    'security.apps.SecurityConfig',


]

# Application definition






PAYPAL_RECEIVER_EMAIL = "your-paypal-email@example.com"

STRIPE_TEST_PUBLIC_KEY = "pk_test_51OQmvuFt0onmnttloiRoZuO637tPGAyw31BmuvJ6RMYL8cIqZYqOsaVQ2CeC1jaBktwbPVSSwCdqV2qNrq8vgAz100CMV4pwLY"
STRIPE_TEST_SECRET_KEY = "sk_test_51OQmvuFt0onmnttlUGNb382Jh3002BSy96f8nowNSNvNdpyouZABGaHV5W6G0DgTCwru4WJvH8t4j7S9vMLOyDiG00mKW2h6rV"

INSTALLED_APPS += [
    'exchange',
    'django_celery_beat',
]





# Թույլատրված IP հասցեների ցանկ
ALLOWED_IPS = [
    '127.0.0.1',
    '5.77.204.102'
    # Ավելացրեք ձեր թույլատրելի IP-ները
]



SUIT_CONFIG = {
    'ADMIN_NAME': 'Ardar_Shop',
    'MENU': (
        'sites',
        'auth',
        'app1',
        'app2',
    )
}







SITE_ID = 1
#
# ACCOUNT_AUTHENTICATION_METHOD = 'email'
# ACCOUNT_EMAIL_REQUIRED = True
# ACCOUNT_USERNAME_REQUIRED = False
# ACCOUNT_EMAIL_VERIFICATION = 'optional'


SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    }
}








AUTHENTICATION_BACKENDS = (

    'social_core.backends.google.GoogleOAuth2',
    # 'allauth.account.auth_backends.AuthenticationBackend',
    'drf_social_oauth2.backends.DjangoOAuth2',
    'django.contrib.auth.backends.ModelBackend',

)








SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile',
]



AUTH_USER_MODEL = 'users.CustomUser'





CORS_ORIGIN_ALLOW_ALL = True


MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'shop.middleware.CurrencyMiddleware',
    'security.middleware.IPWhitelistMiddleware',

    # 'allauth.account.middleware.AccountMiddleware',


]



SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Օգտագործում ենք DB session
SESSION_COOKIE_AGE = 86400  # Session-ը կապրի 24 ժամ (կամ ըստ պահանջի)
SESSION_SAVE_EVERY_REQUEST = True  # Պահպանի session-ը ամեն հարցման ժամանակ
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Չի փակվի browser-ը փակելուց հետո



REDIS_HOST = 'localhost'
REDIS_PORT = 6379
REDIS_DB = 0


ROOT_URLCONF = 'ardar_blog_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
                # "cart.context_processors.CartProcessor",
            ],
        },
    },
]

WSGI_APPLICATION = 'ardar_blog_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


INSTALLED_APPS += ['graphene_django']
GRAPHENE = {
    "SCHEMA": "shop.schema.schema"
}


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'narek_migrated',
#         'USER': 'gevor',
#         'PASSWORD': 'narek1234',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('narek'),
        'USER': os.getenv('narek'),
        'PASSWORD': os.getenv('KSha23n4v9N65FGYLXaTRXeoPyWDIHNF'),
        'HOST': os.getenv('dpg-d0nhd5gdl3ps73a97rn0-a'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}




# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# ELASTICSEARCH_DSL = {
#     'default': {
#         'hosts': ['http://localhost:9200'],
#         # URL ձեր Elasticsearch-ի համար
#     },
# 'AUTOSYNC': False,
# }



# expires in 6 months
oauth2_settings.DEFAULTS['ACCESS_TOKEN_EXPIRE_SECONDS'] = 60



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"




STATICFILES_DIRS = [
    BASE_DIR / 'static',
    # BASE_DIR / 'shop' / 'static',
]

# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, "static"),            # project/static/
#     os.path.join(BASE_DIR, "shop", "static")  # կամ յուրաքանչյուր app/static/
# ]
#
# # Ավարտապես, collectstatic–ը կցուի այս երկու տեղերին
# # եւ հավաքի բոլոր static–երը մեկ output–ում (see STATIC_ROOT)
# STATIC_URL = '/static/'

# # production–ում նախատեսված մեկ միասնական կատալոգ՝ collectstatic–ի համար
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
#
#
# STATICFILES_DIRS = [
#     BASE_DIR / "static",
#     BASE_DIR / "shop/static",
# ]

# STATIC_URL = "static/"
# STATIC_ROOT = "/home/Narek330333/Ardar_Blog/static/"
# MEDIA_URL = "/media/"
# MEDIA_ROOT = "/home/Narek330333/Ardar_Blog/media/"
#



# STATIC_URL = '/static/'
#
# # Աղբյուր–փաթարկների ցուցակում միայն project_root/static
# STATICFILES_DIRS = [
#     BASE_DIR / "static",
# ]
#
# # Production–ում collectstatic–ի թիրախը պակասել չի կարելի
# STATIC_ROOT = BASE_DIR / "staticfiles"
#
# # (Եթե օգտագործում եք WhiteNoise կամ նման storage)
# STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'







REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],


    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        'drf_social_oauth2.authentication.SocialAuthentication',
        'rest_framework.authentication.SessionAuthentication',

    ],
        'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}









# SOCIAL_AUTH_PIPELINE = (
#     'social_core.pipeline.social_auth.social_details',
#     'social_core.pipeline.social_auth.social_uid',
#     'social_core.pipeline.social_auth.auth_allowed',
#     'social_core.pipeline.social_auth.social_user',
#     'social_core.pipeline.user.get_username',
#     'social_core.pipeline.user.create_user',  # Creates the user if not already existing
#     'authentication.pipeline.verify_user',    # Calls our custom function
#     'social_core.pipeline.social_auth.associate_user',
#     'social_core.pipeline.social_auth.load_extra_data',
#     'social_core.pipeline.user.user_details',
# )




# CART

CART_SESSION_ID = 'cart'




load_dotenv()

SECRET_KEY = os.getenv("SECRET_KEY")
DEBUG = os.getenv("DEBUG", "False") == "True"

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")


SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv("SOCIAL_AUTH_GOOGLE_OAUTH2_KEY")
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv("SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET")

EMAIL_BACKEND = os.getenv("EMAIL_BACKEND")
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False") == "True"
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")
EMAIL_FROM = os.getenv("EMAIL_FROM")
EMAIL_BCC = os.getenv("EMAIL_BCC")


EXCHANGE_RATE_API_KEY = os.getenv("EXCHANGE_RATE_API_KEY")



# PAYPAL_LIVE = True  # Production-ի համար (False՝ Sandbox-ի համար)
# PAYPAL_RECEIVER_EMAIL = "your-paypal-email@example.com"
# PAYPAL_CURRENCY = "USD"
# PAYPAL_NOTIFY_URL = "https://yourdomain.com/paypal/ipn/"
# PAYPAL_RETURN_URL = "https://yourdomain.com/payment/success/"
# PAYPAL_CANCEL_URL = "https://yourdomain.com/payment/cancel/"



LANGUAGES = [
    ('en', _('English')),
    ('hy', _('Armenian')),
    ('ru', _('Russian')),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

USE_I18N = True


# PDF Generation Settings
COMPANY_NAME = "NSCompany"
COMPANY_ADDRESS = "Armenia Ararat Norabac"
COMPANY_PHONE = "+374 94876884 +374 94350200"
COMPANY_EMAIL = "NSCompany@gmail.com"
COMPANY_TAX_ID = "TAX-123456789"
COMPANY_LOGO_URL = "/static/images/logo.png"  # Absolute URL preferred

# WeasyPrint configuration
WEASYPRINT_BASEURL = BASE_DIR  # For static files resolution

FRONTEND_HOST = os.environ.get('FRONTEND_HOST', 'http://localhost:3000/')

# SESSION_COOKIE_HTTPONLY = False  # Թույլ է տալիս, որ React-ը session կարդա (անվտանգության հաշվին նվազում է)
# SESSION_COOKIE_SAMESITE = "None"  # Պետք է, եթե frontend-ը ու backend-ը տարբեր դոմեյններում են
# SESSION_COOKIE_SECURE = True  # Պետք է, եթե օգտագործում ես HTTPS


# CORS_ALLOW_CREDENTIALS = True

