# Generated by Django 5.1.7 on 2025-03-31 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ERPIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('erp_type', models.CharField(choices=[('odoo', 'Odoo'), ('sap', 'SAP'), ('dynamics', 'Microsoft Dynamics'), ('netsuite', 'NetSuite')], max_length=20)),
                ('base_url', models.URLField()),
                ('api_key', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_interval', models.PositiveIntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='ERPSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('details', models.JSONField(default=dict)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.erpintegration')),
            ],
        ),
        migrations.CreateModel(
            name='ERPObjectMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('django_model', models.CharField(max_length=100)),
                ('erp_model', models.CharField(max_length=100)),
                ('field_mappings', models.JSONField()),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.erpintegration')),
            ],
            options={
                'unique_together': {('integration', 'django_model')},
            },
        ),
    ]
