# Generated by Django 5.1.7 on 2025-04-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedip',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
