# Generated by Django 5.1.7 on 2025-03-29 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_wishlist_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.sizeprice'),
            preserve_default=False,
        ),
    ]
