# Generated by Django 5.1.5 on 2025-03-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_delivery_service_alter_product_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(null=True, upload_to='subcategory_image/%Y/%m/%d', verbose_name='Ենթակատեգորիայի Նկար'),
        ),
    ]
