# Generated by Django 5.1.5 on 2025-03-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Զեղչված Գին'),
        ),
    ]
