# Generated by Django 5.1.7 on 2025-03-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_wishlist_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizeprice',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
