# Generated by Django 5.1.7 on 2025-03-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_sizeprice_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
