# Generated by Django 5.1.7 on 2025-03-30 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_wishlist_final_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizeprice',
            name='final_price',
        ),
    ]
