# Generated by Django 5.1.7 on 2025-03-30 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_sizeprice_final_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Weight (kg)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='product',
            name='care_instructions',
            field=models.CharField(blank=True, max_length=255, verbose_name='Care Instructions'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.subcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(related_name='products', to='shop.color', verbose_name='Colors'),
        ),
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.CharField(blank=True, max_length=255, verbose_name='Composition'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fit_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Fit Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('Мужской', 'Men'), ('Женский', 'Women'), ('Унисекс', 'Unisex')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_features',
            field=models.CharField(blank=True, max_length=255, verbose_name='Model Features'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pocket_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pocket Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, to='shop.product', verbose_name='Related Products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
    ]
