# Generated by Django 5.1.7 on 2025-05-15 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_product_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['name'], 'verbose_name': 'Size', 'verbose_name_plural': 'Sizes'},
        ),
    ]
