# Generated by Django 5.1.7 on 2025-03-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_color_slug_size_slug_alter_brand_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
