# Generated by Django 5.1.7 on 2025-03-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_subcategory_is_recommended_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='is_recommended',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
