# Generated by Django 5.1.7 on 2025-03-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_subcategory_is_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='is_recommended',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
