# Generated by Django 5.1.7 on 2025-03-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_subcategory_is_recommended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='is_recommended',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='category_image/%Y/%m/%d', verbose_name='Category Image'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_recommended',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
