# Generated by Django 5.1.7 on 2025-03-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_subcategory_is_recommended_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_recommended',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_recommended',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
