# Generated by Django 5.1.7 on 2025-03-11 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_subcategory_is_recommended_category_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountedShowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='DiscountedShow/%Y/%m/%d', verbose_name='Image')),
                ('min_discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('max_discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
    ]
