# Generated by Django 5.1.7 on 2025-03-11 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_discountedshowmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountedshowmodel',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='discountedshowmodel',
            name='max_discount',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='discountedshowmodel',
            name='min_discount',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
