# Generated by Django 5.1.7 on 2025-03-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_wishlist_delete_heartshapedproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='notified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
