# Generated by Django 5.1.7 on 2025-03-15 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_product_price_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_currency',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_currency_currency',
        ),
    ]
