# Generated by Django 5.1.7 on 2025-04-05 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_is_paid_order_notes'),
        ('users', '0004_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.userprofile'),
        ),
    ]
