# Generated by Django 5.1.7 on 2025-05-05 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
