# Generated by Django 5.1.7 on 2025-05-09 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_orderstatushistory_changed_by_and_more'),
        ('users', '0006_customuser_profile_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='users.userprofile'),
        ),
    ]
