# Generated by Django 5.1.7 on 2025-05-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('webmoney', 'WebMoney'), ('card', 'Credit Card')], default='card', max_length=20),
        ),
    ]
