# Generated by Django 5.1.7 on 2025-05-11 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_payment_id_alter_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='currency',
        ),
    ]
